[build]
  publish = "public"
  command = "rm -rf .cache public && npm run build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@lmdb/lmdb-linux-x64", "lmdb", "sharp"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  